Add Gitpod
wagtail/bakerydemo pull request #292
Opened 2021-04-23 21:09 UTC by allcaps

1. Go to https://github.com/allcaps/bakerydemo/
2. Click the Gitpod button
3. Relax

Note: The url in the readme points to my fork. This url needs to be updated on merge. `/allcaps/` => `/wagtail/`.

2021-04-30 15:34 UTC, gasman requested changes
This works really nicely for me!

We might consider updating some of the surrounding text:

* For the intro "If you're new to Python and/or Django...", I think we could recommend Gitpod as the first option - something like "If you want to see what Wagtail is all about, we suggest trying it out through Gitpod. If you want to set up Wagtail locally instead, and you're new to Python and/or Django..."
* The Heroku instructions probably shouldn't start with "If you don't want to test locally", since we've already given people a non-local option. In fact, is there any real reason to keep Heroku around as an alternative at this point?

2021-04-30 15:34 UTC, gasman commented on readme.md
> +Once Gitpod has started, click the preview url to open the website in a new tab.
Suggesting a bit more detail in the instructions, from the perspective of someone who didn't entirely know what to expect from Gitpod startup...
```suggestion
Once Gitpod has fully started and a preview of the bakery website has appeared in the "Simple Browser" panel, click the arrow button to the right of the URL bar to open the website in a new tab.
```

2021-04-30 21:41 UTC, allcaps commented
Thank you for the review!

I applied the requested changes.

> * The Heroku instructions probably shouldn't start with "If you don't want to test locally", since we've already given people a non-local option. In fact, is there any real reason to keep Heroku around as an alternative at this point?

Agreed, the `not locally` is confusing. Heroku is publicly available and persistent, not focused on code. We should keep it. I changed the wording.

2021-05-10 12:16 UTC, gasman approved these changes

2021-05-10 12:18 UTC, gasman commented
Thanks @allcaps! Merged in 4469a5a182f3c34db520979bd257a9a5cc4620fa.

2021-05-10 12:18 UTC, closed without merging